name: campus_car_joco
description: "Campus Car"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  # cupertino icons
  cupertino_icons: ^1.0.6
  # flutter toast
  fluttertoast: ^8.2.4
  # lottie
  lottie: ^2.7.0
  # image picker
  image_picker: ^1.0.5
  # http
  http: ^1.1.2
  # getX
  get: ^4.6.6
  # google mlkit
  google_mlkit_text_recognition: ^0.11.0
  # google fonts
  google_fonts: ^6.1.0
  # reponsive screen
  flutter_screenutil: ^5.9.0
  # svg image
  flutter_svg: ^2.0.9
  # hex color
  hexcolor: ^3.0.1
  # save data local
  shared_preferences: ^2.2.2
  # notification
  awesome_notifications: ^0.8.3
  # color picker
  flutter_material_color_picker: ^1.2.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icon/home_image.svg
    - assets/gif/
    - assets/icon/header_logo_login.jpeg
    - assets/icon/car_park.svg
  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf

